### ISSUE TITLE
db-scheduler/history/all don't work with postgresql 

### ISSUE THREAD

**Issue by rcbose** [bekk/db-scheduler-ui#92]
**Project set up :**
Spring boot 2.7
Java 17
PostgreSQL

**Issue:**
postgresql  driver don't support java.time.Instant type.

Values are always Instant type : Attached screenshot of values
https://github.com/bekk/db-scheduler-ui/blob/main/db-scheduler-ui/src/main/java/no/bekk/dbscheduler/ui/model/TaskRequestParams.java#L34

![image](https://github.com/bekk/db-scheduler-ui/assets/10848527/41de3f37-6938-4245-9bd9-980a13a9ac5a)

**Comment by rcbose** [comment]
I have forked and fided this for me to use it. Please give me access to send pull request. I would like to contirbtue to this and fix some bugs.

**Comment by sergey-volkov-lm** [comment]
@rcbose some folks managed to open PRs. Did you try opening PR via fork?

**Comment by kagkarlsson** [comment]
Yeah, should work via fork, no?
