### ISSUE TITLE
Error when clicking on run/rerun button

### ISSUE THREAD

**Issue by StijnDeLeeuw** [bekk/db-scheduler-ui#97]
## Problem
An error occurs when clicked on the run/rerun button.
From the java console:
```
.w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'scheduleTime' for method parameter type Instant is not present]
```
In the browser console there is an error 400:
```
{
    "timestamp": "2024-04-10T10:01:04.800+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/db-scheduler-api/tasks/rerun"
}
```
## Possible cause 
In #77  the option to schedule was added. In `db-scheduler-ui-frontend/src/services/runTask.ts` there is an optional parameter `scheduleTime` added but in `db-scheduler-ui/src/main/java/no/bekk/dbscheduler/ui/controller/TaskController.java` the parameter isn't optional.
## Possible solution
In `db-scheduler-ui-frontend/src/services/runTask.ts` change
```
scheduleTime&&queryParams.append('scheduleTime', scheduleTime.toISOString());
```
to
```
if (scheduleTime) {
    queryParams.append('scheduleTime', scheduleTime.toISOString());
  } else {
    queryParams.append('scheduleTime', new Date().toISOString());
  }
```
## Extra Information
DB Scheduler version 12.5.0
DB Scheduler UI version 0.7.0
Java 21

**Comment by geirsagberg** [comment]
Seems like a sensible fix! Mind opening a PR?
